quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=pgpass321
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:15432/db_appointment_management

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true

# Auth profile REST Client
quarkus.rest-client.auth-profile-api.url=http://localhost:8081
%prod.quarkus.rest-client.auth-profile-api.url=http://api-auth-profile-v1:8081

# Kafka
kafka.bootstrap.servers=localhost:19092

mp.messaging.outgoing.appointment-events.connector=smallrye-kafka
mp.messaging.outgoing.appointment-events.topic=appointment-events
mp.messaging.outgoing.appointment-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.appointment-events.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.appointment-events.schema.registry.url=http://localhost:8085
mp.messaging.outgoing.appointment-events.auto.register.schemas=true

mp.messaging.incoming.appointment-events-in.connector=smallrye-kafka
mp.messaging.incoming.appointment-events-in.topic=appointment-events
mp.messaging.incoming.appointment-events-in.group.id=appointment-management-group
mp.messaging.incoming.appointment-events-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.appointment-events-in.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.appointment-events-in.schema.registry.url=http://localhost:8085
mp.messaging.incoming.appointment-events-in.specific.avro.reader=true
mp.messaging.incoming.appointment-events-in.auto.offset.reset=earliest